Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Jonathas oliveira Guimarães
// Data atual  : 22/10/2022
Var
// Seção de Declarações das variáveis 
   cont,a,b,n:inteiro
    inicio
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo